name: CI/CD main_yml

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Chenckout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y cmake g++ 

    - name: List files for debug
      run: ls -la

    - name: Add build folder
      run: mkdir build && cd build

    - name: Configure
      run: cmake ..

    - name: Build
      run: make
